export var W = {
  __proto__: null,
  ConcurrentStorage: ConcurrentStorage,
  EventEmitter: EventEmitter,
  URL: _URL,
  UUID: UUID,
  addEvent: addEvent,
  addHashEvent: addHashEvent,
  ajax: ajax,
  base64Decode: base64Decode,
  base64Encode: base64Encode,
  bindReady: bindReady,
  cookie: cookie,
  coverExtend: coverExtend,
  decodeURI: _decodeURI,
  decodeURIComponent: _decodeURIComponent,
  dfmapping: dfmapping,
  each: each,
  encodeDates: encodeDates,
  extend: extend,
  extend2Lev: extend2Lev,
  filter: filter,
  formatDate: formatDate,
  formatJsonString: formatJsonString,
  getCookieTopLevelDomain: getCookieTopLevelDomain,
  getDomBySelector: getDomBySelector,
  getElementContent: getElementContent,
  getHostname: getHostname,
  getIOSVersion: getIOSVersion,
  getQueryParam: getQueryParam,
  getQueryParamsFromUrl: getQueryParamsFromUrl,
  getRandom: getRandom,
  getRandomBasic: getRandomBasic,
  getScreenOrientation: getScreenOrientation,
  getUA: getUA,
  getURL: getURL,
  getURLPath: getURLPath,
  getURLSearchParams: getURLSearchParams,
  hasAttribute: hasAttribute,
  hasAttributes: hasAttributes,
  hashCode: hashCode,
  hashCode53: hashCode53,
  indexOf: indexOf,
  inherit: inherit,
  isArguments: isArguments,
  isArray: isArray,
  isBoolean: isBoolean,
  isDate: isDate,
  isElement: isElement,
  isEmptyObject: isEmptyObject,
  isFunction: isFunction,
  isHttpUrl: isHttpUrl,
  isIOS: isIOS,
  isJSONString: isJSONString,
  isNumber: isNumber,
  isObject: isObject,
  isString: isString,
  isSupportBeaconSend: isSupportBeaconSend,
  isSupportCors: isSupportCors,
  isUndefined: isUndefined,
  jsonp: jsonp,
  listenPageState: listenPageState,
  loadScript: loadScript,
  localStorage: _localStorage,
  logger: logger,
  map: map,
  mediaQueriesSupported: mediaQueriesSupported,
  now: now,
  removeScriptProtocol: removeScriptProtocol,
  rot13defs: rot13defs,
  rot13obfs: rot13obfs,
  ry: ry,
  safeJSONParse: safeJSONParse,
  searchObjDate: searchObjDate,
  sessionStorage: _sessionStorage,
  setCssStyle: setCssStyle,
  strToUnicode: strToUnicode,
  throttle: throttle,
  toArray: toArray,
  trim: trim,
  unique: unique,
  urlParse: urlParse,
  urlSafeBase64: urlSafeBase64,
  values: values,
  xhr: xhr
};


export var common = {
  __proto__: null,
  parseSuperProperties: parseSuperProperties,
  searchConfigData: searchConfigData,
  strip_empty_properties: strip_empty_properties,
  getCurrentDomain: getCurrentDomain,
  getEleInfo: getEleInfo,
  isBaiduTraffic: isBaiduTraffic,
  getReferrerEqid: getReferrerEqid,
  getReferrerEqidType: getReferrerEqidType,
  getBaiduKeyword: getBaiduKeyword,
  isReferralTraffic: isReferralTraffic,
  getReferrer: getReferrer,
  getKeywordFromReferrer: getKeywordFromReferrer,
  getWxAdIdFromUrl: getWxAdIdFromUrl,
  getReferSearchEngine: getReferSearchEngine,
  getSourceFromReferrer: getSourceFromReferrer,
  info: pageInfo,
  ajax: ajax$1,
  getElementContent: getElementContent$1,
  cookie: cookie$1,
  addEvent: addEvent$1,
  EventEmitterSa: EventEmitterSa,
  encrypt: encrypt,
  decryptIfNeeded: decryptIfNeeded
};

export var functions = {
  __proto__: null,
  addReferrerHost: addReferrerHost,
  addPropsHook: addPropsHook,
  initPara: initPara,
  setInitVar: setInitVar,
  enableLocalLog: enableLocalLog,
  disableLocalLog: disableLocalLog,
  quick: quick,
  use: use,
  track: track,
  bind: bind,
  unbind: unbind,
  trackLink: trackLink,
  trackLinks: trackLinks,
  setItem: setItem,
  deleteItem: deleteItem,
  setProfile: setProfile,
  setOnceProfile: setOnceProfile,
  appendProfile: appendProfile,
  incrementProfile: incrementProfile,
  deleteProfile: deleteProfile,
  unsetProfile: unsetProfile,
  identify: identify,
  trackSignup: trackSignup,
  registerPage: registerPage,
  clearAllRegister: clearAllRegister,
  clearPageRegister: clearPageRegister,
  register: register,
  registerOnce: registerOnce,
  registerSession: registerSession,
  registerSessionOnce: registerSessionOnce,
  login: login,
  loginWithKey: loginWithKey,
  logout: logout,
  getPresetProperties: getPresetProperties,
  iOSWebClickPolyfill: iOSWebClickPolyfill,
  readyState: readyState,
  para_default: defaultPara,
  log: sdLog,
  debug: debug,
  IDENTITY_KEY: IDENTITY_KEY,
  on: eventEmitterFacade
};

export var saEmpty = {
  track: function(e, p, c) {},
  quick: function(name, p, t, c) {},
  register: function(obj) {},
  registerPage: function(obj) {},
  registerOnce: function(obj) {},
  clearAllRegister: function(arr) {},
  trackSignup: function(id, e, p, c) {},
  setProfile: function(prop, c) {},
  setOnceProfile: function(prop, c) {},
  appendProfile: function(prop, c) {},
  incrementProfile: function(prop, c) {},
  deleteProfile: function(c) {},
  unsetProfile: function(prop, c) {},
  identify: function(id, isSave) {},
  login: function(id, callback) {},
  logout: function(isChangeId) {},
  trackLink: function(link, event_name, event_prop) {},
  deleteItem: function(type, id) {},
  setItem: function(type, id, p) {},
  getAppStatus: function(func) {},
  clearPageRegister: function(arr) {}
};